---
title: "code improvements"
output: html_notebook
---

# library

```{r}
library(bench)
library(tidyverse)
library(tictoc)
```

[bench](https://www.tidyverse.org/blog/2018/06/bench-1.0.1/)で測る。毎回シミュレーション結果は異なるのだが、それだとエラーが出るので`check = FALSE`にする。


# unbiased transmission

populationをtibbleではなくvectorに格納する意義の検証

```{r}
# original

unbiased_transmission_1 <- function(population_size, timesteps) {
  
  population <- tibble(trait = sample(c("A", "B"), population_size, replace = TRUE))

  output <- tibble(timestep = 1:timesteps, proportion_of_trait_a = rep(NA, timesteps))

  output$proportion_of_trait_a[1] <- sum(population$trait == "A") / population_size

  for (timestep in 2:timesteps) {
    
    # Copy individuals to previous_population tibble
    previous_population <- population 
    
    # Randomly copy from previous generation
    population <- sample(previous_population, population_size, replace = TRUE)
    
    # Get p and put it into output slot for this generation t
    output$proportion_of_trait_a[timestep] <- sum(population$trait == "A") / population_size
  }
  # Export data from function
  output
}
# matsui
model_unbiased_transmission_1 <- function(population_size, timesteps) {
  
  population <- sample(c("A", "B"), population_size, replace = TRUE)

  output <- tibble(timestep = 1:timesteps, proportion_of_trait_a = rep(NA, timesteps))

  output$proportion_of_trait_a[1] <- sum(population == "A") / population_size

  for (timestep in 2:timesteps) {
    
    # Copy individuals to previous_population tibble
    previous_population <- population 
    
    # Randomly copy from previous generation
    population <- sample(previous_population, population_size, replace = TRUE)
    
    # Get p and put it into output slot for this generation t
    output$proportion_of_trait_a[timestep] <- sum(population == "A") / population_size
  }
  # Export data from function
  output
}


bench_1_1 <- bench::mark(
  original = unbiased_transmission_1(population_size = 1000, timesteps = 100),
  ours = model_unbiased_transmission_1(population_size = 1000, timesteps = 100),
  
  iterations = 100,
  relative = TRUE,
  check = FALSE)
bench_1_1 %>% autoplot()
bench_1_1
```
2倍程度の高速化、メモリー1/3



```{r}
model_unbiased_transmissions <- function(population_size, timesteps, runs) {
  output <- tibble(run = numeric(), timestep = numeric(), proportion_of_trait_a = numeric())
  # 毎回の試行
  for (run in 1:runs) {
    # １回の試行の結果を保管するtibbleを初期化
    output_single_run <- tibble(run = rep(run, timesteps), timestep = 1:timesteps, proportion_of_trait_a = rep(NA, timesteps))
    # 第1世代
    population <- sample(c("A", "B"), population_size, replace = TRUE)
    # 第１世代のproportion_of_trait_aを計算
    proportion_of_trait_a <- sum(population == "A") / population_size
    output_single_run$proportion_of_trait_a[1] <- proportion_of_trait_a
    for (timestep in 2:timesteps) {
      # 前タイムステップまでのpopulationベクトルをprevious_populationに移し替える
      previous_population <- population
      # ランダムに前世代の個人から形質をコピーする
      population <- sample(previous_population, population_size, replace = TRUE)
      # proportion_of_trait_aを計算し、tibbleのうちproportion_of_trait_a列のtimestep行目に格納する
      output_single_run$proportion_of_trait_a[timestep] <- sum(population == "A") / population_size
    }
    # output tibbleの一番下に今回の試行の結果をbind_rows()関数で付け加える
    output <- bind_rows(output, output_single_run)
  }
  # 全試行の結果がひとつのoutputというtibbleに集約されたので、それを返り値としてエクスポートする
  output
}


unbiased_transmission_2 <- function(N, t_max, r_max) {
  output <- tibble(generation = rep(1:t_max, r_max), 
                   p = as.numeric(rep(NA, t_max * r_max)), 
                   run = as.factor(rep(1:r_max, each = t_max))) 
  # For each run
  for (r in 1:r_max) { 
    # Create first generation
    population <- tibble(trait = sample(c("A", "B"), N, replace = TRUE))
    
    # Add first generation's p for run r
    output[output$generation == 1 & output$run == r, ]$p <-
      sum(population$trait == "A") / N 
    
    # For each generation
    for (t in 2:t_max) {
      # Copy individuals to previous_population tibble
      previous_population <- population 
      
      # Randomly copy from previous generation
      population <- tibble(trait = sample(previous_population$trait, N, replace = TRUE))
      
      # Get p and put it into output slot for this generation t and run r
      output[output$generation == t & output$run == r, ]$p <- 
        sum(population$trait == "A") / N 
    }
  }
    # Export data from function
  output 
}

bench_1_2 <- bench::mark(
  original = unbiased_transmission_2(N = 1000, t_max = 100, r_max = 5),
  ours = model_unbiased_transmissions(population_size = 1000, timesteps = 100, runs = 5),
  iterations = 100,
  relative = TRUE,
  check = FALSE)
bench_1_2
bench_1_2 %>% autoplot()
```
7.5倍程度はやくメモリーも1/3.7


# 2

```{r}

unbiased_mutation <- function(N, mu, p_0, t_max, r_max) {
  # Create the output tibble
  output <- tibble(generation = rep(1:t_max, r_max), 
                   p = as.numeric(rep(NA, t_max * r_max)), 
                   run = as.factor(rep(1:r_max, each = t_max))) 

  for (r in 1:r_max) {
    population <- tibble(trait = sample(c("A", "B"), N, replace = TRUE, 
                                        prob = c(p_0, 1 - p_0)))
    # Add first generation's p for run r
    output[output$generation == 1 & output$run == r, ]$p <- 
      sum(population$trait == "A") / N 
    for (t in 2:t_max) {
      # Copy individuals to previous_population tibble
      previous_population <- population 
      
      # Determine 'mutant' individuals
      mutate <- sample(c(TRUE, FALSE), N, prob = c(mu, 1 - mu), replace = TRUE) 
      
      # If there are 'mutants' from A to B
      if (nrow(population[mutate & previous_population$trait == "A", ]) > 0) { 
        # Then flip them to B
        population[mutate & previous_population$trait == "A", ]$trait <- "B" 
      }
      
      # If there are 'mutants' from B to A
      if (nrow(population[mutate & previous_population$trait == "B", ]) > 0) { 
        # Then flip them to A
        population[mutate & previous_population$trait == "B", ]$trait <- "A" 
      }
      
      # Get p and put it into output slot for this generation t and run r
      output[output$generation == t & output$run == r, ]$p <- 
        sum(population$trait == "A") / N 
    }
  }
  # Export data from function
  output 
}

model_unbiased_mutation_intermediate <- function(population_size, mutation_rate, initial_probability_of_trait_a, timesteps, runs) {
  output <- tibble(run = numeric(), timestep = numeric(), proportion_of_trait_a = numeric())

  for (run in 1:runs) {

    output_single_run <- tibble(run = rep(run, timesteps),timestep = 1:timesteps, proportion_of_trait_a = rep(NA, timesteps))
    # initialize population
    population <- sample(c("A", "B"), population_size, replace = TRUE, prob = c(initial_probability_of_trait_a, 1 - initial_probability_of_trait_a))
    # initialize first generation's p
    proportion_of_trait_a <- sum(population == "A") / population_size
    output_single_run$proportion_of_trait_a[1] <- proportion_of_trait_a
    for (timestep in 2:timesteps) {
      previous_population <- population
       should_mutate <- sample(c(TRUE, FALSE), population_size, prob = c(mutation_rate, 1 - mutation_rate), replace = TRUE)
 if (length(population[should_mutate & previous_population == "A"]) > 0) { 
        # Then flip them to B
        population[should_mutate & previous_population == "A"] <- "B" 
      }
      
      # If there are 'mutants' from B to A
      if (length(population[should_mutate & previous_population == "B"]) > 0) { 
        # Then flip them to A
        population[should_mutate & previous_population == "B"] <- "A" 
      }
            output_single_run$proportion_of_trait_a[timestep] <- sum(population == "A") / population_size
    }
  output <- bind_rows(output, output_single_run)
  }
  output
}



model_unbiased_mutation_old <- function(population_size,timesteps, runs,initial_probability_of_trait_a,mutation_rate) {
  output <- tibble(run = numeric(), timestep = numeric(), proportion_of_trait_a = numeric())

  for (run in 1:runs) {

    output_single_run <- tibble(run = rep(run, timesteps),timestep = 1:timesteps, proportion_of_trait_a = rep(NA, timesteps))
    # initialize population
    population <- sample(c("A", "B"), population_size, replace = TRUE, prob = c(initial_probability_of_trait_a, 1 - initial_probability_of_trait_a))
    # initialize first generation's p
    proportion_of_trait_a <- sum(population == "A") / population_size
    output_single_run$proportion_of_trait_a[1] <- proportion_of_trait_a
    for (timestep in 2:timesteps) {
      previous_population <- population
       should_mutate <- sample(c(TRUE, FALSE), population_size, prob = c(mutation_rate, 1 - mutation_rate), replace = TRUE)
       population <- if_else(should_mutate, if_else(population == "A", "B", "A"), population)
      output_single_run$proportion_of_trait_a[timestep] <- sum(population == "A") / population_size
    }
  output <- bind_rows(output, output_single_run)
  }
  output
}

model_unbiased_mutation <- function(
  population_size,
  generations,
  runs, 
  initial_proportion_of_trait_a,
  mutation_rate) {
  tic("total")
  output <- tibble(
    run = factor(), 
    generation = numeric(), 
    proportion_of_trait_a = numeric()
  )
  for (run in 1:runs) {
    output_single_run <- tibble(
      run = rep(run, generations) %>% as.factor(), 
      generation = 1:generations, 
      proportion_of_trait_a = rep(NA, generations)
    )
    tic("population generation")
    population <- sample(
      c("A", "B"), 
      population_size, replace = TRUE, 
      prob = c(initial_proportion_of_trait_a, 1 - initial_proportion_of_trait_a)
    )
    toc()
    tic("proportion")
    proportion_of_trait_a <- sum(population == "A") / population_size
    toc()
    tic("proportion dainyu")
    output_single_run$proportion_of_trait_a[1] <- proportion_of_trait_a
    toc()
    

        for (generation in 2:generations) {
          tic("one gen")
      previous_population <- population
      is_mutant <- sample(
        c(TRUE, FALSE), 
        population_size, 
        prob = c(mutation_rate, 1 - mutation_rate),
        replace = TRUE
      )
      population[is_mutant] <- population[is_mutant] |> recode(A = "B", B = "A")
      output_single_run$proportion_of_trait_a[generation] <- 
      sum(population == "A") / population_size
    }
    output <- bind_rows(output, output_single_run)
  }
  output
}



model_unbiased_mutation2 <- function(
  population_size,
  generations,
  runs, 
  initial_proportion_of_trait_a,
  mutation_rate) {
  output <- tibble(
    run = factor(), 
    generation = numeric(), 
    proportion_of_trait_a = numeric()
  )
  for (run in 1:runs) {
    output_single_run <- tibble(
      run = rep(run, generations) %>% as.factor(), 
      generation = 1:generations, 
      proportion_of_trait_a = rep(NA, generations)
    )
    population <- sample(
      c(TRUE, FALSE), # 変更点
      population_size, replace = TRUE, 
      prob = c(initial_proportion_of_trait_a, 1 - initial_proportion_of_trait_a)
    ) 
    proportion_of_trait_a <- sum(population) / population_size # 変更点
    output_single_run$proportion_of_trait_a[1] <- proportion_of_trait_a
    for (generation in 2:generations) {
      previous_population <- population
      is_mutant <- sample(
        c(TRUE, FALSE), 
        population_size, 
        prob = c(mutation_rate, 1 - mutation_rate),
        replace = TRUE
      )
      population[is_mutant] <- !population[is_mutant]  # 変更点
      output_single_run$proportion_of_trait_a[generation] <- 
      sum(population) / population_size # 変更点
    }
    output <- bind_rows(output, output_single_run)
  }
  output
}
!c(TRUE, FALSE) 

vec <- c(F, F, T, T, F, T, T)
is_mutant <- c(F, F,F, F, T, T, F)
vec[is_mutant] <- !vec[is_mutant]
vec
tic()
model_unbiased_mutation(1000, 100, 5, 0.5, 0.05)
toc()
tic()
model_unbiased_mutation2(1000, 100, 5, 0.5, 0.05)
toc()
tic()
model_unbiased_mutation_old(1000, 100, 5, 0.5, 0.05)
toc()
model_unbiased_mutation_intermediate(population_size = 1000, mutation_rate = 0.05, 0.5, timesteps = 100, runs = 5)
bench_2_1 <- bench::mark(
      ours_truefalse = model_unbiased_mutation2(1000, 100, 5, 0.5, 0.05),
    # ours_intermediate = model_unbiased_mutation_intermediate(population_size = 1000, mutation_rate = 0.05, 0.5, timesteps = 100, runs = 5),
  ours = model_unbiased_mutation(1000, 100, 5, 0.5, 0.05),
  # original = unbiased_mutation(N = 1000, mu = 0.05, p_0 = 0.5, t_max = 100, r_max = 5),

  iterations = 50,
  relative = TRUE,
  check = FALSE)
bench_2_1
bench_2_1 |> autoplot()
```
oursにくらべ、true falseのものは2倍速い。オリジナルに比べ、oursは4倍以上速い。



```{r}
model_biased_transmission_direct <- function (
  population_size, 
  probability_a, 
  probability_b,
  initial_proportion_of_trait_a,
  generations,
  runs) {
  output <- tibble(
    run = factor(), 
    generation = numeric(), 
    proportion_of_trait_a = numeric()
  )
  for (run in 1:runs) {
    # 1回の試行の結果を保管するtibbleを初期化
    output_single_run <- tibble(
      run = rep(run, generations) |> as.factor(), 
      generation = 1:generations, 
      proportion_of_trait_a = rep(NA, generations)
    )
    # 第1世代
    population <- sample(
      c("A", "B"), 
      population_size, replace = TRUE, 
      prob = c(initial_proportion_of_trait_a, 1 - initial_proportion_of_trait_a)
    )
    # 第1世代のproportion_of_trait_aを計算
    proportion_of_trait_a <- sum(population == "A") / population_size
    output_single_run$proportion_of_trait_a[1] <- proportion_of_trait_a
    for (generation in 2:generations) {
      # 前タイムステップまでのpopulationベクトルをprevious_populationに移し替える
      previous_population <- population
      # 今timestepの集団に属する個人は、それぞれデモンストレーターを前世代から適当に一人指名する
      demonstrator_trait <- sample(previous_population, population_size, replace = TRUE)
      # バイアスのあるコピー確率でコピーするか否かを決める
      should_copy_a <- sample(
        c(TRUE, FALSE),
        population_size,
        prob = c(probability_a, 1 - probability_a),
        replace = TRUE
      )
      should_copy_b <- sample(
        c(TRUE, FALSE),
        population_size,
        prob = c(probability_b, 1 - probability_b),
        replace = TRUE
      )
      population <- case_when(
        demonstrator_trait == "A" & should_copy_a ~ "A",
        demonstrator_trait == "B" & should_copy_b ~ "B",
        TRUE ~ previous_population
      )
      # proportion_of_trait_aを計算し、tibbleのうち
      # proportion_of_trait_a列のgeneration行目に格納する
      output_single_run$proportion_of_trait_a[generation] <- 
      sum(population == "A") / population_size
    }
    # output tibbleの一番下に今回の試行の結果をbind_rows()関数で付け加える
    output <- bind_rows(output, output_single_run)
  }
  # 全試行の結果がひとつのoutputというtibbleに集約されたので、それを返り値としてエクスポートする
  output
}
biased_transmission_direct <- function (N, s_a, s_b, p_0, t_max, r_max) {
  
  output <- tibble(generation = rep(1:t_max, r_max), 
                   p = as.numeric(rep(NA, t_max * r_max)), 
                   run = as.factor(rep(1:r_max, each = t_max)))
  
  for (r in 1:r_max) {
    # Create first generation
    population <- tibble(trait = sample(c("A", "B"), N, 
                                        replace = TRUE, prob = c(p_0, 1 - p_0))) 
    
    # Add first generation's p for run r
    output[output$generation == 1 & output$run == r, ]$p <- 
      sum(population$trait == "A") / N 

    for (t in 2:t_max) {
      # Copy individuals to previous_population tibble
      previous_population <- population 
      
      # For each individual, pick a random individual from the previous generation
      demonstrator_trait <- 
        tibble(trait = sample(previous_population$trait, N, replace = TRUE)) 
      
      # Biased probabilities to copy:
      copy_a <- sample(c(TRUE, FALSE), N, prob = c(s_a, 1 - s_a), replace = TRUE) 
      copy_b <- sample(c(TRUE, FALSE), N, prob = c(s_b, 1 - s_b), replace = TRUE) 
      
      # If the demonstrator has trait A and the individual wants to copy A, then copy A
      if (nrow(population[copy_a & demonstrator_trait$trait == "A", ]) > 0) {
        population[copy_a & demonstrator_trait$trait == "A", ]$trait <- "A" 
      }  
      
      # If the demonstrator has trait B and the individual wants to copy B, then copy B
      if (nrow(population[copy_b & demonstrator_trait$trait == "B", ]) > 0) {
        population[copy_b & demonstrator_trait$trait == "B", ]$trait <- "B" 
      }  
      # Get p and put it into output slot for this generation t and run r
      output[output$generation == t & output$run == r, ]$p <- 
        sum(population$trait == "A") / N 
    }
  }
  # Export data from function
  output 
}
bench_3_1 <- bench::mark(
      ours = model_biased_transmission_direct(10000, .1, 0, .01, 150, 1),
  original = biased_transmission_direct(10000, .1, 0, .01, 150, 1),
  iterations = 15,
  relative = TRUE,
  check = FALSE)
bench_3_1
bench_3_1 |> autoplot()

```
```{r}
model_biased_transmission_direct2 <- function (
  population_size, 
  probability_a, 
  probability_b,
  initial_proportion_of_trait_a,
  generations,
  runs) {
  output <- tibble(
    run = factor(), 
    generation = numeric(), 
    proportion_of_trait_a = numeric()
  )
  # prepare T/F vector for all runs and generations
  # should each individual copy a (or b)?
  sample_size <- population_size * generations * runs
  should_copy_a_everyone <- sample(
        c(TRUE, FALSE),
        sample_size,
        prob = c(probability_a, 1 - probability_a),
        replace = TRUE
      )
  should_copy_b_everyone <- sample(
        c(TRUE, FALSE),
        sample_size,
        prob = c(probability_b, 1 - probability_b),
        replace = TRUE
      )
  for (run in 1:runs) {
    # 1回の試行の結果を保管するtibbleを初期化
    output_single_run <- tibble(
      run = rep(run, generations) |> as.factor(), 
      generation = 1:generations, 
      proportion_of_trait_a = rep(NA, generations)
    )
    # 第1世代
    population <- sample(
      c("A", "B"), 
      population_size, replace = TRUE, 
      prob = c(initial_proportion_of_trait_a, 1 - initial_proportion_of_trait_a)
    )
    # 第1世代のproportion_of_trait_aを計算
    proportion_of_trait_a <- sum(population == "A") / population_size
    output_single_run$proportion_of_trait_a[1] <- proportion_of_trait_a
    for (generation in 2:generations) {
      # 今timestepの集団に属する個人は、それぞれデモンストレーターを前世代から適当に一人指名する
      is_demonstrator_trait_a <- sample(population, population_size, replace = TRUE) == "A"

      # バイアスのあるコピー確率でコピーするか否かを決める
      used_slots <- population_size * generations * (run - 1) + population_size * (generation - 1) 
      which_slot <- used_slots + 1:population_size
      should_copy_a <- is_demonstrator_trait_a & should_copy_a_everyone[which_slot]
      should_copy_b <- !is_demonstrator_trait_a & should_copy_b_everyone[which_slot]
      
      # population <- case_when(
      #   demonstrator_trait == "A" & should_copy_a ~ "A",
      #   demonstrator_trait == "B" & should_copy_b ~ "B",
      #   TRUE ~ population
      # )
      if(length(should_copy_a) > 0) {
        population[should_copy_a] <- "A"}
      if(length(should_copy_b) > 0) {
        population[should_copy_b] <- "B"}
      # proportion_of_trait_aを計算し、tibbleのうち
      # proportion_of_trait_a列のgeneration行目に格納する
      output_single_run$proportion_of_trait_a[generation] <- 
      sum(population == "A") / population_size
    }
    # output tibbleの一番下に今回の試行の結果をbind_rows()関数で付け加える
    output <- bind_rows(output, output_single_run)
  }
  # 全試行の結果がひとつのoutputというtibbleに集約されたので、それを返り値としてエクスポートする
  output
}

tic()
model_biased_transmission_direct2(10000, .1, 0, .01, 150, 10) |> plot_multiple_runs()
toc()
```

